# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Publish

# Trigger the workflow's on pushed version tags.
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/test-docs.yaml"
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/test-docs.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  # Builds and pushes docker images to DockerHub and package the Helm chart and
  # pushes it to jupyterhub/helm-chart@gh-pages where index.yaml represents the
  # JupyterHub organization Helm chart repository.
  #
  # ref: https://github.com/jupyterhub/helm-chart
  # ref: https://hub.docker.com/orgs/jupyterhub
  #
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install build package
        run: |
          pip install build
          pip list

      - name: build release
        run: |
          python -m build --sdist --wheel .
          ls -alh dist

      # ref: https://github.com/pypa/gh-action-pypi-publish
      - name: publish to pypi
        if: startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
