# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Publish

# Trigger the workflow's on pushed version tags.
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/test-docs.yaml"
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/test-docs.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: "3.13"

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          package-manager-cache: false

      - name: install build requirements
        run: |
          pip install --upgrade pip
          pip install build
          pip list --format=freeze

      - name: build release
        run: |
          python -m build --sdist --wheel .
          ls -l dist

      # ref: https://github.com/actions/upload-artifact#readme
      - name: upload dists
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: ${{ github.repository.name }}-dist
          path: dist/

  pypi-publish:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: release
    needs:
      - build-release
    permissions:
      id-token: write

    steps:
      - name: Get release artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ github.repository.name }}-dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
